### ISSUE TITLE
Incorrect "Assertion on 'schema' failed: Must have length 1, but has length 2"

### ISSUE THREAD

**Issue by m1p1h** [darwin-eu/CDMConnector#28]
I'm looking to generate a cdm reference object from a databricks db (in a catalog=main and schema=omop) via odbc connector. It can connect ok but when I try to generate the reference using following code I get what appears to be an incorrect assertion error.

```R
cdm <- cdm_from_con(con = con, 
                    cdm_schema = "main.omop", 
                    write_schema = "main.omop")
```
I've tried which gives the same error:

```R
cdm <- cdm_from_con(con = con, 
                    cdm_schema = c(catalog="main", schema="omop"), 
                    write_schema = c(catalog="main", schema="omop"))
```
The [docs](https://search.r-project.org/CRAN/refmans/CDMConnector/html/cdm_from_con.html) suggest either of those approaches are valid.

I'm using the latest CDMConnector v1.5.0 and I have full permissions on the databricks catalog.

Any suggestions?

**Comment by ablack3** [comment]
You're correct that either approach should work and that this is a bug. I'm working on fixing it.

**Comment by ablack3** [comment]
I was able to test this. First install the development branch.

```
remotes::install_github("darwin-eu/CDMConnector", "develop")
```

Then I ran this code which worked.

```
  con <- DBI::dbConnect(
    odbc::databricks(),
    httpPath = Sys.getenv("DATABRICKS_HTTPPATH"),
    useNativeQuery = FALSE
  )

  cdm <- cdmFromCon(con = con,
                    cdmSchema = "hive_metastore.gibleed",
                    writeSchema = "hive_metastore.scratch")


  cdm <- cdmFromCon(con = con,
                    cdmSchema = c(catalog="hive_metastore", schema="gibleed"),
                    writeSchema = c(catalog="hive_metastore", schema="scratch"))

  cdmDisconnect(cdm)
```
