### ISSUE TITLE
Typo in benchmarkCDMConnector

### ISSUE THREAD

**Issue by cecicampanile** [darwin-eu/CDMConnector#32]
We believe there is a typo in benchmarkCDMConnector:
https://github.com/darwin-eu/CDMConnector/blob/af064fce69819baaa8288640b9287a7d3b2a725a/R/benchmarkCDMConnector.R#L97-L103
the table to be joined with person should be observation_period
@ablack3

**Comment by catalamarti** [comment]
hi @ablack3, @cecicampanile is working with us and she would be happy to open a PR to fix it.

**Comment by ablack3** [comment]
Thanks for the issue @cecicampanile. I fixed this in our development repo and it will be released by the end of the week.
